version: "3.8"
services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.multi
    #   target: api-build
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - rag_api
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
      - PORT=${PORT}
      - DOMAIN_CLIENT=${DOMAIN_CLIENT}
      - DOMAIN_SERVER=${DOMAIN_SERVER}
      - NO_INDEX=${NO_INDEX}
      - CONSOLE_JSON=${CONSOLE_JSON}
      - DEBUG_LOGGING=${DEBUG_LOGGING}
      - DEBUG_CONSOLE=${DEBUG_CONSOLE}
      - PROXY=${PROXY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - BINGAI_TOKEN=${BINGAI_TOKEN}
      - GOOGLE_KEY=${GOOGLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG_OPENAI=${DEBUG_OPENAI}
      - ASSISTANTS_API_KEY=${ASSISTANTS_API_KEY}
      - DEBUG_PLUGINS=${DEBUG_PLUGINS}
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      - AZURE_AI_SEARCH_SERVICE_ENDPOINT=${AZURE_AI_SEARCH_SERVICE_ENDPOINT}
      - AZURE_AI_SEARCH_INDEX_NAME=${AZURE_AI_SEARCH_INDEX_NAME}
      - AZURE_AI_SEARCH_API_KEY=${AZURE_AI_SEARCH_API_KEY}
      - AZURE_AI_SEARCH_API_VERSION=${AZURE_AI_SEARCH_API_VERSION}
      - AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE=${AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE}
      - AZURE_AI_SEARCH_SEARCH_OPTION_TOP=${AZURE_AI_SEARCH_SEARCH_OPTION_TOP}
      - AZURE_AI_SEARCH_SEARCH_OPTION_SELECT=${AZURE_AI_SEARCH_SEARCH_OPTION_SELECT}
      - GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - SD_WEBUI_URL=${SD_WEBUI_URL}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - TRAVERSAAL_API_KEY=${TRAVERSAAL_API_KEY}
      - WOLFRAM_APP_ID=${WOLFRAM_APP_ID}
      - ZAPIER_NLA_API_KEY=${ZAPIER_NLA_API_KEY}
      - SEARCH=${SEARCH}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - OPENAI_MODERATION=${OPENAI_MODERATION}
      - OPENAI_MODERATION_API_KEY=${OPENAI_MODERATION_API_KEY}
      - BAN_VIOLATIONS=${BAN_VIOLATIONS}
      - BAN_DURATION=${BAN_DURATION}
      - BAN_INTERVAL=${BAN_INTERVAL}
      - LOGIN_VIOLATION_SCORE=${LOGIN_VIOLATION_SCORE}
      - REGISTRATION_VIOLATION_SCORE=${REGISTRATION_VIOLATION_SCORE}
      - CONCURRENT_VIOLATION_SCORE=${CONCURRENT_VIOLATION_SCORE}
      - MESSAGE_VIOLATION_SCORE=${MESSAGE_VIOLATION_SCORE}
      - NON_BROWSER_VIOLATION_SCORE=${NON_BROWSER_VIOLATION_SCORE}
      - LOGIN_MAX=${LOGIN_MAX}
      - LOGIN_WINDOW=${LOGIN_WINDOW}
      - REGISTER_MAX=${REGISTER_MAX}
      - REGISTER_WINDOW=${REGISTER_WINDOW}
      - LIMIT_CONCURRENT_MESSAGES=${LIMIT_CONCURRENT_MESSAGES}
      - CONCURRENT_MESSAGE_MAX=${CONCURRENT_MESSAGE_MAX}
      - LIMIT_MESSAGE_IP=${LIMIT_MESSAGE_IP}
      - MESSAGE_IP_MAX=${MESSAGE_IP_MAX}
      - MESSAGE_IP_WINDOW=${MESSAGE_IP_WINDOW}
      - LIMIT_MESSAGE_USER=${LIMIT_MESSAGE_USER}
      - MESSAGE_USER_MAX=${MESSAGE_USER_MAX}
      - MESSAGE_USER_WINDOW=${MESSAGE_USER_WINDOW}
      - ILLEGAL_MODEL_REQ_SCORE=${ILLEGAL_MODEL_REQ_SCORE}
      - CHECK_BALANCE=${CHECK_BALANCE}
      - ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION}
      - ALLOW_SOCIAL_LOGIN=${ALLOW_SOCIAL_LOGIN}
      - ALLOW_SOCIAL_REGISTRATION=${ALLOW_SOCIAL_REGISTRATION}
      - SESSION_EXPIRY=${SESSION_EXPIRY}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_CALLBACK_URL=${DISCORD_CALLBACK_URL}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - FACEBOOK_CALLBACK_URL=${FACEBOOK_CALLBACK_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - OPENID_CLIENT_ID=${OPENID_CLIENT_ID}
      - OPENID_CLIENT_SECRET=${OPENID_CLIENT_SECRET}
      - OPENID_ISSUER=${OPENID_ISSUER}
      - OPENID_SESSION_SECRET=${OPENID_SESSION_SECRET}
      - OPENID_SCOPE=${OPENID_SCOPE}
      - OPENID_CALLBACK_URL=${OPENID_CALLBACK_URL}
      - OPENID_REQUIRED_ROLE=${OPENID_REQUIRED_ROLE}
      - OPENID_REQUIRED_ROLE_TOKEN_KIND=${OPENID_REQUIRED_ROLE_TOKEN_KIND}
      - OPENID_REQUIRED_ROLE_PARAMETER_PATH=${OPENID_REQUIRED_ROLE_PARAMETER_PATH}
      - OPENID_BUTTON_LABEL=${OPENID_BUTTON_LABEL}
      - OPENID_IMAGE_URL=${OPENID_IMAGE_URL}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_ENCRYPTION=${EMAIL_ENCRYPTION}
      - EMAIL_ENCRYPTION_HOSTNAME=${EMAIL_ENCRYPTION_HOSTNAME}
      - EMAIL_ALLOW_SELFSIGNED=${EMAIL_ALLOW_SELFSIGNED}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - EMAIL_FROM=${EMAIL_FROM}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - APP_TITLE=${APP_TITLE}
      - HELP_AND_FAQ_URL=${HELP_AND_FAQ_URL}
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
  client:
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: prod-stage
    container_name: LibreChat-NGINX
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: always
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
  mongodb:
    container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - HOST=${HOST}
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - DOMAIN_CLIENT=${DOMAIN_CLIENT}
      - DOMAIN_SERVER=${DOMAIN_SERVER}
      - NO_INDEX=${NO_INDEX}
      - CONSOLE_JSON=${CONSOLE_JSON}
      - DEBUG_LOGGING=${DEBUG_LOGGING}
      - DEBUG_CONSOLE=${DEBUG_CONSOLE}
      - PROXY=${PROXY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - BINGAI_TOKEN=${BINGAI_TOKEN}
      - GOOGLE_KEY=${GOOGLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG_OPENAI=${DEBUG_OPENAI}
      - ASSISTANTS_API_KEY=${ASSISTANTS_API_KEY}
      - DEBUG_PLUGINS=${DEBUG_PLUGINS}
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      - AZURE_AI_SEARCH_SERVICE_ENDPOINT=${AZURE_AI_SEARCH_SERVICE_ENDPOINT}
      - AZURE_AI_SEARCH_INDEX_NAME=${AZURE_AI_SEARCH_INDEX_NAME}
      - AZURE_AI_SEARCH_API_KEY=${AZURE_AI_SEARCH_API_KEY}
      - AZURE_AI_SEARCH_API_VERSION=${AZURE_AI_SEARCH_API_VERSION}
      - AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE=${AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE}
      - AZURE_AI_SEARCH_SEARCH_OPTION_TOP=${AZURE_AI_SEARCH_SEARCH_OPTION_TOP}
      - AZURE_AI_SEARCH_SEARCH_OPTION_SELECT=${AZURE_AI_SEARCH_SEARCH_OPTION_SELECT}
      - GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - SD_WEBUI_URL=${SD_WEBUI_URL}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - TRAVERSAAL_API_KEY=${TRAVERSAAL_API_KEY}
      - WOLFRAM_APP_ID=${WOLFRAM_APP_ID}
      - ZAPIER_NLA_API_KEY=${ZAPIER_NLA_API_KEY}
      - SEARCH=${SEARCH}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS}
      - MEILI_HOST=${MEILI_HOST}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - OPENAI_MODERATION=${OPENAI_MODERATION}
      - OPENAI_MODERATION_API_KEY=${OPENAI_MODERATION_API_KEY}
      - BAN_VIOLATIONS=${BAN_VIOLATIONS}
      - BAN_DURATION=${BAN_DURATION}
      - BAN_INTERVAL=${BAN_INTERVAL}
      - LOGIN_VIOLATION_SCORE=${LOGIN_VIOLATION_SCORE}
      - REGISTRATION_VIOLATION_SCORE=${REGISTRATION_VIOLATION_SCORE}
      - CONCURRENT_VIOLATION_SCORE=${CONCURRENT_VIOLATION_SCORE}
      - MESSAGE_VIOLATION_SCORE=${MESSAGE_VIOLATION_SCORE}
      - NON_BROWSER_VIOLATION_SCORE=${NON_BROWSER_VIOLATION_SCORE}
      - LOGIN_MAX=${LOGIN_MAX}
      - LOGIN_WINDOW=${LOGIN_WINDOW}
      - REGISTER_MAX=${REGISTER_MAX}
      - REGISTER_WINDOW=${REGISTER_WINDOW}
      - LIMIT_CONCURRENT_MESSAGES=${LIMIT_CONCURRENT_MESSAGES}
      - CONCURRENT_MESSAGE_MAX=${CONCURRENT_MESSAGE_MAX}
      - LIMIT_MESSAGE_IP=${LIMIT_MESSAGE_IP}
      - MESSAGE_IP_MAX=${MESSAGE_IP_MAX}
      - MESSAGE_IP_WINDOW=${MESSAGE_IP_WINDOW}
      - LIMIT_MESSAGE_USER=${LIMIT_MESSAGE_USER}
      - MESSAGE_USER_MAX=${MESSAGE_USER_MAX}
      - MESSAGE_USER_WINDOW=${MESSAGE_USER_WINDOW}
      - ILLEGAL_MODEL_REQ_SCORE=${ILLEGAL_MODEL_REQ_SCORE}
      - CHECK_BALANCE=${CHECK_BALANCE}
      - ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION}
      - ALLOW_SOCIAL_LOGIN=${ALLOW_SOCIAL_LOGIN}
      - ALLOW_SOCIAL_REGISTRATION=${ALLOW_SOCIAL_REGISTRATION}
      - SESSION_EXPIRY=${SESSION_EXPIRY}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_CALLBACK_URL=${DISCORD_CALLBACK_URL}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - FACEBOOK_CALLBACK_URL=${FACEBOOK_CALLBACK_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - OPENID_CLIENT_ID=${OPENID_CLIENT_ID}
      - OPENID_CLIENT_SECRET=${OPENID_CLIENT_SECRET}
      - OPENID_ISSUER=${OPENID_ISSUER}
      - OPENID_SESSION_SECRET=${OPENID_SESSION_SECRET}
      - OPENID_SCOPE=${OPENID_SCOPE}
      - OPENID_CALLBACK_URL=${OPENID_CALLBACK_URL}
      - OPENID_REQUIRED_ROLE=${OPENID_REQUIRED_ROLE}
      - OPENID_REQUIRED_ROLE_TOKEN_KIND=${OPENID_REQUIRED_ROLE_TOKEN_KIND}
      - OPENID_REQUIRED_ROLE_PARAMETER_PATH=${OPENID_REQUIRED_ROLE_PARAMETER_PATH}
      - OPENID_BUTTON_LABEL=${OPENID_BUTTON_LABEL}
      - OPENID_IMAGE_URL=${OPENID_IMAGE_URL}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_ENCRYPTION=${EMAIL_ENCRYPTION}
      - EMAIL_ENCRYPTION_HOSTNAME=${EMAIL_ENCRYPTION_HOSTNAME}
      - EMAIL_ALLOW_SELFSIGNED=${EMAIL_ALLOW_SELFSIGNED}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - EMAIL_FROM=${EMAIL_FROM}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - APP_TITLE=${APP_TITLE}
      - HELP_AND_FAQ_URL=${HELP_AND_FAQ_URL}
    volumes:
      - ./meili_data_v1.7:/meili_data
  vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
      - HOST=${HOST}
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - DOMAIN_CLIENT=${DOMAIN_CLIENT}
      - DOMAIN_SERVER=${DOMAIN_SERVER}
      - NO_INDEX=${NO_INDEX}
      - CONSOLE_JSON=${CONSOLE_JSON}
      - DEBUG_LOGGING=${DEBUG_LOGGING}
      - DEBUG_CONSOLE=${DEBUG_CONSOLE}
      - PROXY=${PROXY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - BINGAI_TOKEN=${BINGAI_TOKEN}
      - GOOGLE_KEY=${GOOGLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG_OPENAI=${DEBUG_OPENAI}
      - ASSISTANTS_API_KEY=${ASSISTANTS_API_KEY}
      - DEBUG_PLUGINS=${DEBUG_PLUGINS}
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      - AZURE_AI_SEARCH_SERVICE_ENDPOINT=${AZURE_AI_SEARCH_SERVICE_ENDPOINT}
      - AZURE_AI_SEARCH_INDEX_NAME=${AZURE_AI_SEARCH_INDEX_NAME}
      - AZURE_AI_SEARCH_API_KEY=${AZURE_AI_SEARCH_API_KEY}
      - AZURE_AI_SEARCH_API_VERSION=${AZURE_AI_SEARCH_API_VERSION}
      - AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE=${AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE}
      - AZURE_AI_SEARCH_SEARCH_OPTION_TOP=${AZURE_AI_SEARCH_SEARCH_OPTION_TOP}
      - AZURE_AI_SEARCH_SEARCH_OPTION_SELECT=${AZURE_AI_SEARCH_SEARCH_OPTION_SELECT}
      - GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - SD_WEBUI_URL=${SD_WEBUI_URL}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - TRAVERSAAL_API_KEY=${TRAVERSAAL_API_KEY}
      - WOLFRAM_APP_ID=${WOLFRAM_APP_ID}
      - ZAPIER_NLA_API_KEY=${ZAPIER_NLA_API_KEY}
      - SEARCH=${SEARCH}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS}
      - MEILI_HOST=${MEILI_HOST}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - OPENAI_MODERATION=${OPENAI_MODERATION}
      - OPENAI_MODERATION_API_KEY=${OPENAI_MODERATION_API_KEY}
      - BAN_VIOLATIONS=${BAN_VIOLATIONS}
      - BAN_DURATION=${BAN_DURATION}
      - BAN_INTERVAL=${BAN_INTERVAL}
      - LOGIN_VIOLATION_SCORE=${LOGIN_VIOLATION_SCORE}
      - REGISTRATION_VIOLATION_SCORE=${REGISTRATION_VIOLATION_SCORE}
      - CONCURRENT_VIOLATION_SCORE=${CONCURRENT_VIOLATION_SCORE}
      - MESSAGE_VIOLATION_SCORE=${MESSAGE_VIOLATION_SCORE}
      - NON_BROWSER_VIOLATION_SCORE=${NON_BROWSER_VIOLATION_SCORE}
      - LOGIN_MAX=${LOGIN_MAX}
      - LOGIN_WINDOW=${LOGIN_WINDOW}
      - REGISTER_MAX=${REGISTER_MAX}
      - REGISTER_WINDOW=${REGISTER_WINDOW}
      - LIMIT_CONCURRENT_MESSAGES=${LIMIT_CONCURRENT_MESSAGES}
      - CONCURRENT_MESSAGE_MAX=${CONCURRENT_MESSAGE_MAX}
      - LIMIT_MESSAGE_IP=${LIMIT_MESSAGE_IP}
      - MESSAGE_IP_MAX=${MESSAGE_IP_MAX}
      - MESSAGE_IP_WINDOW=${MESSAGE_IP_WINDOW}
      - LIMIT_MESSAGE_USER=${LIMIT_MESSAGE_USER}
      - MESSAGE_USER_MAX=${MESSAGE_USER_MAX}
      - MESSAGE_USER_WINDOW=${MESSAGE_USER_WINDOW}
      - ILLEGAL_MODEL_REQ_SCORE=${ILLEGAL_MODEL_REQ_SCORE}
      - CHECK_BALANCE=${CHECK_BALANCE}
      - ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION}
      - ALLOW_SOCIAL_LOGIN=${ALLOW_SOCIAL_LOGIN}
      - ALLOW_SOCIAL_REGISTRATION=${ALLOW_SOCIAL_REGISTRATION}
      - SESSION_EXPIRY=${SESSION_EXPIRY}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_CALLBACK_URL=${DISCORD_CALLBACK_URL}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - FACEBOOK_CALLBACK_URL=${FACEBOOK_CALLBACK_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - OPENID_CLIENT_ID=${OPENID_CLIENT_ID}
      - OPENID_CLIENT_SECRET=${OPENID_CLIENT_SECRET}
      - OPENID_ISSUER=${OPENID_ISSUER}
      - OPENID_SESSION_SECRET=${OPENID_SESSION_SECRET}
      - OPENID_SCOPE=${OPENID_SCOPE}
      - OPENID_CALLBACK_URL=${OPENID_CALLBACK_URL}
      - OPENID_REQUIRED_ROLE=${OPENID_REQUIRED_ROLE}
      - OPENID_REQUIRED_ROLE_TOKEN_KIND=${OPENID_REQUIRED_ROLE_TOKEN_KIND}
      - OPENID_REQUIRED_ROLE_PARAMETER_PATH=${OPENID_REQUIRED_ROLE_PARAMETER_PATH}
      - OPENID_BUTTON_LABEL=${OPENID_BUTTON_LABEL}
      - OPENID_IMAGE_URL=${OPENID_IMAGE_URL}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_ENCRYPTION=${EMAIL_ENCRYPTION}
      - EMAIL_ENCRYPTION_HOSTNAME=${EMAIL_ENCRYPTION_HOSTNAME}
      - EMAIL_ALLOW_SELFSIGNED=${EMAIL_ALLOW_SELFSIGNED}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - EMAIL_FROM=${EMAIL_FROM}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - APP_TITLE=${APP_TITLE}
      - HELP_AND_FAQ_URL=${HELP_AND_FAQ_URL}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env

volumes:
  pgdata2:
